### ISSUE TITLE
node 12.16.1 on Catalina installation

### ISSUE THREAD

**Issue by zeg-io** [iamthefox/luxafor#10]
This module unfortunately breaks when I attempt to install it onto a mac with macOS Catalina [10.15.4 (19E266)] with node 12.16.1 installed on it. It seems the dev tools aren't compatible with the node-gyp rebuild.

**Comment by iamthefox** [comment]
Hi @zeg-io, this package was abandoned for a while. I finally had some time to clean it up and just published version 3 which should work with recent versions of node as well as clean up api and add couple features. Let me know if it is still broken for you.

**Comment by zeg-io** [comment]
Awesome! Thank you. And now we know what the fox says!  😄 🦊
