### ISSUE TITLE
Node 18 npm install errors

### ISSUE THREAD

**Issue by fifofonix** [iamthefox/luxafor#19]
On MacOS I'm having to pin node@16 to `npm install luxafor-api` cleanly and use the package.

When I try with node@18 I get npm errors referencing dynamic exception specifications, e.g:

```
...
npm ERR! ../src/HID.cc:67:5: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
npm ERR!     throw(JSException);
npm ERR!     ^~~~~~~~~~~~~~~~~~
...
```

**Comment by iamthefox** [comment]
Hi @fifofonix I've just published a new version which should be compatible with node@16 and node@18.

**Comment by fifofonix** [comment]
Awesome.  Really appreciate it.  Unpinned node@16.  Have so enjoyed using the Luxafor light thanks to this easy tooling.
