### ISSUE TITLE
Can't work on Raspberry Pi

### ISSUE THREAD

**Issue by jsdario** [iamthefox/luxafor#3]
I worked through the eventual bugs (as `target = undefined`), however now it does not prompt any errors.
Is there a way to get err management or feedback from this lib?

**Comment by iamthefox** [comment]
hey @jsdario, 
Error management is not something I have a lot of experience with.

Would be great if you could give me the idea of how you see it working.

**Comment by jsdario** [comment]
Well the most common options would be two:
1. For those functions that throw an error **do not catch it** unless it is a solution. Throw it to the user output, so the developer using your software can now use `try /catch`.
2. Asynchronous functions should always return an error as first parameter, to check wether during its task they have failed or not, a typical `asyncfunction(function (err) { ... } )``

So for example in this file and line https://github.com/iamthefox/luxafor/blob/master/src/luxafor.js#L51 it would be better just to throw the error, because else to prove it you'd have to check for `Luxafor.device isInstanceOf Error` which is quite inconvenient.

**Comment by intotheweb101** [comment]
Anymore more ground on this?
