### ISSUE TITLE
Question: Manage 2 Luxafors sepratly

### ISSUE THREAD

**Issue by intotheweb101** [iamthefox/luxafor#4]
Hello 

I have 2 Luxafors and I want to set different colors on each of them.  Do you know of a way of doing this?

Thanks

**Comment by iamthefox** [comment]
Hello, 

I never thought about it, but I feel like this should be implemented.

I have multiple luxafors so for the next few days I will try to implement this missing bit of functionality :)

Thank you for your feedback

**Comment by iamthefox** [comment]
Implemented in 3.0
