### ISSUE TITLE
Example documentation leads to runtime errors

### ISSUE THREAD

**Issue by fatso83** [iamthefox/luxafor#6]
The example docs lead to a `undefined` error. This is due to this line:
```
117     target = typeof target !== 'undefined' ? target : this.opts.defaults.setColor.target;                                                                                                                                                                                      
```
In the example docs you don't set a `setColor.target`, meaning `setColor` will be undefined and you end up with ` TypeError: Cannot read property 'target' of undefined`.

**Comment by iamthefox** [comment]
This should not be an issue anymore.
